"""Seed the admin user and the starter dataset catalog.

The catalog is three datasets, generated deterministically on first launch so
a fresh clone has real data to work with and no downloads are required:

* **Healthy Campus** — a realistic quarter of hourly readings per appliance.
* **Fault Simulation Campus** — the same estate with faults injected.
* **BDG2 Electricity Meters** — the committed open-source meter export,
  adapted to the platform schema (whole-building metering, no invented rooms).

Anomalies and defects are injected into the CSVs unlabelled; the quality and
anomaly stages discover them from the data, which is what makes those screens
honest. The seed registers inputs and stops.

Run:  python seed.py
"""

from __future__ import annotations

import sys
from datetime import timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from app.core.config import settings
from app.core.security import hash_password
from app.db.base import SessionLocal, init_db
from app.db.models import (
    Dataset,
    DatasetBuilding,
    DatasetDevice,
    DatasetFloor,
    DatasetRoom,
    User,
)
from app.domain.hierarchy import GRANULARITY_ASSET, GRANULARITY_METER
from app.domain.synth import SEED, build_campus, build_reference

ADMIN_EMAIL = "admin@ecomind.ai"
ADMIN_PASSWORD = "admin123"

DAYS = 90

CATALOG = [
    {
        "name": "EcoMind Healthy Campus (90-day hourly)",
        "csv": "ecomind_healthy_campus.csv",
        "profile": "healthy",
        "source_type": "sample",
        "granularity": GRANULARITY_ASSET,
        "badges": {"healthy": True, "reference": False, "controlled_pair": True},
        "description": (
            "Two commercial buildings instrumented down to the appliance, hourly "
            "for a quarter. A realistic operating baseline with only a few subtle "
            "outliers, light sensor gaps and repeated readings."
        ),
        "provenance": {
            "origin": "Synthetic (generated by backend/app/domain/synth.py)",
            "license": "MIT (generated)",
            "collection_method": "Simulation with physical plausibility constraints",
            "geographic_scope": "Synthetic two-building campus",
            "version": "2.0",
            "random_seed": SEED,
            "citation": "Generated data. Not a measurement of any real building.",
        },
    },
    {
        "name": "EcoMind Fault Simulation Campus (90-day hourly)",
        "csv": "ecomind_fault_campus.csv",
        "profile": "faulty",
        "source_type": "sample",
        "granularity": GRANULARITY_ASSET,
        "badges": {"healthy": False, "reference": False, "controlled_pair": True},
        "description": (
            "The same two-building estate with faults injected: power spikes, "
            "night-time waste, a failed HVAC zone, sensor dropouts, voltage sag, "
            "occupancy/load mismatches and stuck meters. The controlled pair is "
            "for demonstrating the quality and anomaly stages."
        ),
        "provenance": {
            "origin": "Synthetic (generated by backend/app/domain/synth.py)",
            "license": "MIT (generated)",
            "collection_method": "Simulation with deliberately injected faults",
            "geographic_scope": "Synthetic two-building campus",
            "version": "2.0",
            "random_seed": SEED,
            "citation": "Generated data with injected faults. Not a measurement.",
        },
    },
    {
        "name": "BDG2 Electricity Meters (3-year hourly, open data)",
        "csv": "ecomind_reference_meters.csv",
        "profile": "reference",
        "source_type": "reference",
        "granularity": GRANULARITY_METER,
        "badges": {"healthy": False, "reference": True, "controlled_pair": False},
        "doi": "10.5281/zenodo.3898439",
        "source_url": "https://zenodo.org/record/3898439",
        "license": "CC BY 4.0 — UCI ElectricityLoadDiagrams20112014 (Trindade, 2015)",
        "description": (
            "Three years of real, open hourly whole-building electricity meters "
            "projected onto the platform schema. Meter granularity: Building › "
            "Meter, with no room-level instrumentation invented."
        ),
        "provenance": {
            "origin": "Open data — UCI ElectricityLoadDiagrams20112014 via Zenodo 3898439",
            "license": "CC BY 4.0",
            "collection_method": "Real meter readings, projected to the 14-column schema",
            "doi": "10.5281/zenodo.3898439",
            "source_url": "https://zenodo.org/record/3898439",
            "citation": "Trindade, A. (2015). ElectricityLoadDiagrams20112014. UCI ML Repository.",
            "version": "1.0",
        },
    },
]


def _frame_for(spec: dict):
    if spec["profile"] in ("healthy", "faulty"):
        return build_campus(spec["profile"], days=DAYS, seed=SEED)
    return build_reference()


def _monthly_rows(df) -> int:
    if df.empty:
        return 0
    month = df["timestamp"].dt.to_period("M")
    return int(df.assign(_m=month).groupby(["building_code", "device_code", "_m"]).ngroups)


def _register(db, user: User, spec: dict, df, tree, make_active: bool) -> Dataset:
    csv_path = settings.generated_dir / spec["csv"]
    df.to_csv(csv_path, index=False)

    buildings = tree["buildings"]
    floors = tree["floors"]
    rooms = tree["rooms"]
    devices = tree["devices"]

    dataset = Dataset(
        user_id=user.id,
        name=spec["name"],
        description=spec["description"],
        source_type=spec["source_type"],
        file_path=str(csv_path),
        file_size_bytes=csv_path.stat().st_size,
        row_count=int(len(df)),
        column_count=int(df.shape[1]),
        granularity=spec["granularity"],
        is_active=make_active,
        building_count=len(buildings),
        floor_count=len(floors),
        room_count=len(rooms),
        device_count=len(devices),
        hourly_row_count=int(len(df)),
        monthly_row_count=_monthly_rows(df),
        defect_rate=round(float(df.isna().to_numpy().mean()), 4),
        doi=spec.get("doi"),
        source_url=spec.get("source_url"),
        license=spec.get("license"),
        badges=spec["badges"],
        provenance=spec["provenance"],
        status="ready",
    )
    db.add(dataset)
    db.flush()

    for row in buildings:
        db.add(DatasetBuilding(dataset_id=dataset.id, **row))
    for row in floors:
        db.add(DatasetFloor(dataset_id=dataset.id, **row))
    for row in rooms:
        db.add(DatasetRoom(dataset_id=dataset.id, **row))
    for row in devices:
        db.add(DatasetDevice(dataset_id=dataset.id, **row))
    return dataset


def seed() -> None:
    init_db()
    db = SessionLocal()
    try:
        user = db.query(User).filter(User.email == ADMIN_EMAIL).first()
        if user is None:
            user = User(
                email=ADMIN_EMAIL,
                hashed_password=hash_password(ADMIN_PASSWORD),
                full_name="Admin User",
                role="admin",
            )
            db.add(user)
            db.flush()
            print(f"Created admin {ADMIN_EMAIL}")

        has_active = (
            db.query(Dataset).filter(Dataset.is_active.is_(True)).first() is not None
        )
        added = 0
        for spec in CATALOG:
            if db.query(Dataset).filter(Dataset.name == spec["name"]).first():
                print(f"Present: {spec['name']}")
                continue
            built = _frame_for(spec)
            if built is None:
                print(f"Skipped (source missing): {spec['name']}")
                continue
            df, tree, meta = built
            make_active = not has_active
            _register(db, user, spec, df, tree, make_active)
            has_active = has_active or make_active
            added += 1
            print(
                f"Registered: {spec['name']} — {len(df):,} rows x {df.shape[1]} cols, "
                f"{len(tree['rooms'])} rooms, {len(tree['devices'])} devices"
            )

        db.commit()
        print(f"\nCatalog ready. Added {added} dataset(s).")
        print(f"Login: {ADMIN_EMAIL} / {ADMIN_PASSWORD}")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
